### ISSUE TITLE
Scrollspy

### ISSUE THREAD

**Issue by Shadow-Talent** [MahdiMajidzadeh/materialize-rtl#13]
Scrollspy (Navbar Fixed Top Shode & Sidenav  Ro) Dochare Moshkel Mikone.
Hatman Az Firefox Estefade Konid, Inspect Element Chrome In Bug Ro Neshoon Nemide.

1-History Firefox Ro Clear Konid.
2-Ye Navbar Besazid Va Navbar-Fixed Konid.
3-Hala Scrollspy Ro Add Konid.
4-Az Mozila (Inspect > Resonsive Design) Chandin Device Ro Test Konid.
5-Ro Link haye Navbar / Sidenav Click Konid.
A : Kole Navbar / Sidenav Be Samte Bala Taghire Position Mide.
B : Navbar / Sidenav Baraye Chand Sec Invisible Va Dobare Visible Mishe.

Ye Moshkele Dige Ham Inke Vaghti Az Scrollspy Estefade Mikonim Age Too Navbar / Sidenav Az Material Icons Ya Font Awsome Estefade Konim Dar Soorati Ke Roo Icon Ha Click Konim Smooth Scroll Kar Nemikone Vali Ba Click Kardan Roo Matne Link Smooth Scroll Kar Mikone.
Tashakor Babate Zahamaatetoon.

**Comment by MahdiMajidzadeh** [comment]
Hi,
I wasn't editing js files and this issue came from original repo and codes
