### ISSUE TITLE
Any plan for further release?

### ISSUE THREAD

**Issue by sumit4code** [MahdiMajidzadeh/materialize-rtl#3]
Any plan for further release?

**Comment by JafarAkhondali** [comment]
May i ask why didn't you fork the original repository? I think you'll have hard time update your repo..

**Comment by merajiyan** [comment]
I need swipeable tabs which needs further version please update it

**Comment by A-Programmer** [comment]
Is this repo alive still?
I mean do you want to continue?

**Comment by MahdiMajidzadeh** [comment]
hi
I waiting to release version 1.0 to continue

**Comment by Obka** [comment]
hi
version 1.0 is release can you continue ?

**Comment by MahdiMajidzadeh** [comment]
I started

**Comment by MahdiMajidzadeh** [comment]
repo updated
thanks for your patient
