### ISSUE TITLE
tabs problem

### ISSUE THREAD

**Issue by grabli1989** [MahdiMajidzadeh/materialize-rtl#5]
What about the tabs? I click on one tab it is selected, but the other is highlighted. Thank!

**Comment by grabli1989** [comment]
I solved this problem as follows:
I set for ul attribute dir="ltr" and arranged the list items in the desired order.

**Comment by merajiyan** [comment]
i have the same problem

**Comment by MahdiMajidzadeh** [comment]
issue resolved in the latest version of Materialize
and repo updated too
